name: Build and Push to Docker Hub
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 1' # Elke maandag automatisch bouwen voor updates
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: bird4ever/docker-playwright:latest
